### ISSUE TITLE
some picture not ready to download

### ISSUE THREAD

**Issue by pasagame** [squix78/esp8266-weather-station-color#8]
some picture not ready

Loading image 'chancetstorms.bmp'
Loading image '/mini/chancetstorms.bmp'

**Comment by gabeszakem** [comment]
Have you any solution?

**Comment by G6EJD** [comment]
No, the file should exists unless it was never downloaded

**Comment by KarlNorway** [comment]
If yiu test the links in the first post, they are not present

**Comment by pasagame** [comment]
thank you

**Comment by G6EJD** [comment]
The file name is correct 'chance of thunder storms' so the t should be there. Weather underground do not use BMP formatted files so at some point they have all been converted and are downloaded from Daniels server to the ESP spiffs storage, he must have missed that file out which is why it's not found.
